#ifndef _UNIT_TYPE_H
#define _UNIT_TYPE_H

#define UNIT_TYPE_INDEPENDENT		0x80
#define UNIT_TYPE_UNITY					0x81
#define UNIT_TYPE_UNITY_RFID		0x82

//#define UNIT_TYPE			UNIT_TYPE_UNITY			
//#define UNIT_TYPE			UNIT_TYPE_INDEPENDENT

#define SUPPLIES_NUM	10
#define SENSOR_NUM	6

#define FW_VERSION_MAJOR				0x01
#define FW_VERSION_MINOR				0x00

#endif
